const simpsons = {
  mainCharacters: [ 
    {
      name: "Homer Simpson",
      sex: "male",
      occupation: "Nuclear Safety Inspector",
      friends: ["Barney", "Carl", "Lenny", "Moe"]
    },
    {
      name: "Marge Simpson",
      sex: "female",
      occupation: "Housewife"
    },
    {
      name: "Bart Simpson",
      sex: "male",
      occupation: "Student",
      friends: ["Milhouse", "Nelson", "Ralph", "Jessica"]
    },
    {
      name: "Lisa Simpson",
      sex: "female",
      occupation: "Student"
    },
    {
      name: "Maggie Simpson",
      sex: "female",
      occupation: "N/A"
    }
  ],
  allCharacters:[
  "Homer Simpson",
  "Marge Simpson",
  "Bart Simpson",
  "Lisa Simpson",
  "Maggie Simpson",
  "Akira",
  "Ms. Albright",
  "Aristotle Amadopolis",
  "Atkins, State Comptroller",
  "Mary Bailey",
  "Birchibald \"Birch\" T. Barlow",
  "Jasper Beardly",
  "Benjamin, Doug, and Gary",
  "Bill and Marty",
  "Blinky",
  "Blue Haired Lawyer[13]",
  "Boobarella",
  "Wendell Borton",
  "Jacqueline Bouvier",
  "Patty Bouvier",
  "Selma Bouvier",
  "Kent Brockman",
  "Bumblebee Man",
  "Charles Montgomery Burns",
  "Capital City Goofball",
  "Carl Carlson",
  "Mrs. Carlson",
  "Crazy Cat Lady",
  "Gary Chalmers",
  "Charlie",
  "Chase (Pyro)",
  "Scott Christian",
  "Comic Book Guy",
  "Mr. Costington",
  "Database",
  "Declan Desmond",
  "Disco Stu",
  "Dolph",
  "Lunchlady Doris",
  "Duffman",
  "Eddie and Lou",
  "Fat Tony",
  "Maude Flanders",
  "Ned Flanders",
  "Rod Flanders",
  "Todd Flanders",
  "Francesca",
  "Frankie the Squealer",
  "Professor John Frink",
  "Baby Gerald",
  "Ginger Flanders",
  "Gino Terwilliger",
  "Alice Glick",
  "Gloria Jailbird",
  "Barney Gumble",
  "Gil Gunderson",
  "The Happy Little Elves",
  "Judge Constance Harm",
  "Herman Hermann",
  "Bernice Hibbert",
  "Dr. Julius Hibbert",
  "Elizabeth Hoover",
  "Lionel Hutz",
  "Itchy & Scratchy",
  "Jacques",
  "Jimbo Jones",
  "Rachel Jordan",
  "Kang and Kodos",
  "Princess Kashmir",
  "Edna Krabappel",
  "Rabbi Hyman Krustofski",
  "Krusty the Clown",
  "Cookie Kwan",
  "Dewey Largo",
  "Legs and Louie",
  "Leopold",
  "Lenny Leonard",
  "Lewis Clark",
  "Helen Lovejoy",
  "Reverend Timothy Lovejoy",
  "Coach Lugash",
  "Lurleen Lumpkin",
  "Otto Mann",
  "Captain Horatio McCallister",
  "Roger Meyers, Jr.",
  "Troy McClure",
  "Hans Moleman",
  "Dr. Marvin Monroe",
  "Nelson Muntz",
  "Captain Lance Murdock",
  "Bleeding Gums Murphy",
  "Lindsey Naegle",
  "Apu Nahasapeemapetilon",
  "Manjula Nahasapeemapetilon",
  "Sanjay Nahasapeemapetilon",
  "Jake[39]",
  "Old Jewish Man",
  "Patches and Poor Violet",
  "Arnie Pye",
  "Herbert Powell",
  "Janey Powell",
  "Ruth Powers",
  "Martin Prince",
  "Loren Pryor",
  "Mayor \"Diamond\" Joe Quimby",
  "Radioactive Man",
  "The Rich Texan",
  "Richard",
  "Luigi Risotto",
  "Dr. Nick Riviera",
  "Santa's Little Helper",
  "Sherri and Terri",
  "Dave Shutton",
  "Robert Terwilliger",
  "Sideshow Mel",
  "Grampa Simpson",
  "Amber Simpson",
  "Mona Simpson",
  "Agnes Skinner",
  "Seymour Skinner",
  "Waylon Smithers",
  "Snake Jailbird",
  "Snowball II",
  "Roy Snyder",
  "Jebediah Springfield",
  "Cletus Spuckler",
  "Brandine Spuckler",
  "Squeaky-Voiced Teen",
  "Moe Szyslak",
  "Drederick Tatum",
  "Allison Taylor",
  "Mr. Teeny",
  "Cecil Terwilliger",
  "Johnny Tightlips",
  "Üter Zörker",
  "Kirk Van Houten",
  "Luann Van Houten",
  "Milhouse Van Houten",
  "Dr. Velimirovic",
  "Police Chief Clancy Wiggum",
  "Ralph Wiggum",
  "Sarah Wiggum",
  "Groundskeeper Willie",
  "Raphael",
  "Rainier Wolfcastle (McBain)",
  "The Yes Guy[11]",
  "Artie Ziff",
  "Kearney Zzyzwicz"
],
  families: {
    carlson: {
      husband: "Carl Carlson",
      wife: "Mrs. Carlson"
    },
    flanders: {
      husband: "Ned Flanders",
      wife: "Maude Flanders",
      children: [
        "Rod Flanders",
        "Todd Flanders"
      ]
    },
    nahasapeemapetilon: {
      husband: "Apu Nahasapeemapetilon",
      wife: "Manjula Nahasapeemapetilon",
    },
    simpson: {
      husband: "Homer Simpson",
      wife: "Marge Simpson",
      children: [
        "Bart Simpson",
        "Lisa Simpson",
        "Maggie Simpson"
      ]
    },
    vanHouten: {
      husband: "Kirk Van Houten",
      wife: "Luann Van Houten",
      children: ["Milhouse Van Houten"]
    },
    wiggum: {
      husband: "Police Chief Clancy Wiggum",
      wife: "Sarah Wiggum",
      children: ["Ralph Wiggum"]
    }
  },
  locations: {
    popular: {
      kwikEMart: {
        name: "kwik-E-mart",
        owner: "Apu Nahasapeemapetilon",
        occupants: "Most of Springfield"
      },
      moesTavern: {
        name: "Moe's Tavern",
        owner: "Moe Szyslak",
        occupants: [
          "Homer Simpson",
          "Lenny Leonard",
          "Carl Carlson",
          "Barney Gumble"
        ]
      },
      powerPlant: {
        name: "Springfield Nuclear Power Plant",
        owner: "Charles Montgomery Burns",
        occupants: "Employees"
      },
      krustyBurger:{
        name: "Krusty Burger",
        owner: "Krusty the Clown",
        occupants: "Most of Springfield",
        menu: [
          "Krusty Burger",
          "Double Krusty Burger",
          "Deep Fried Krusty Burger",
          "Mother Nature Burger (discontinued)",
          "Double Double Double Double",
          "Salad (not actually served)",
          "Yogurt (not actually served)",
          "Meat-Flavored Sandwich",
          "The Clogger",
          "Ribwich (limited time only; discontinued)",
          "Filly Fudge Steak (discontinued)",
          "Bacon Balls (discontinued)",
          "Whatchamachicken (discontinued)",
          "Fish Sandwich",
          "Krusty-Partially-Gelatinated-Non-Dairy-Gum-Based-Beverage",
          "Krusty Popcorn",
          "Frosted Krusty Flakes",
          "Whatchamacarcass Sandwich",
          "Breakfast Balls",
          "Gravy Scrapems",
          "Twisty Lard",
          "Super-Choker Burritos with Macho Sauce"
        ]
      },
      simpsonHome: {
        name: "Simpsons Home",
        owner: "Ned Flanders",
        occupants: "The Simposons Family",
        address: "742 Evergreen Terrace"
      },
      school: {
        name: "Springfield Elementary School",
        owner: [
          "State Comptroller Atkins",
          "Gary Chalmers"
        ],
        occupants: {
          faculty: [
            "Art teacher (unnamed)",
            "State Comptroller Atkins",
            "Ballet Teacher (unnamed)",
            "Jasper Beardly",
            "Mr. Becker",
            "Mr. Bergstrom",
            "Caroline Berrera",
            "Black Teacher (unnamed)",
            "Calliope Juniper",
            "Gary Chalmers",
            "Dahlia Brinkley",
            "Dick Testiclees",
            "Mr. Estes",
            "Evelyn Trunch",
            "Doris Freedman",
            "Groundskeeper Seamus",
            "Groundskeeper Willie",
            "Gym Teacher (unnamed)",
            "Mrs. Harvell",
            "Elizabeth Hoover",
            "Jim Hope",
            "Jack Lassen",
            "Ms. Kelp",
            "Kindergarten Teacher (unnamed)",
            "Kindergarten Teacher (Lisa's Sax)",
            "Edna Krabappel",
            "Coach Krupt",
            "Dewey Largo",
            "Leopold",
            "Otto Mann",
            "Math teacher (unnamed)",
            "Audrey McConnell",
            "Melanie Upfoot",
            "Meredith Milgram",
            "Mike Benzie",
            "Mr. Glascock",
            "Mr. Hippie",
            "Mr. Johnson",
            "Mr. Kupferberg",
            "Mr. Somerset",
            "Ms. Barr",
            "Ms. Cantwell",
            "Ms. Dubinsky",
            "Ms. Myles",
            "Myra",
            "Ms. Phipps",
            "Brunella Pommelhorst",
            "Principal Hartly",
            "J. Loren Pryor",
            "Tito Puente (character)",
            "Quinn Hopper",
            "Seymour Skinner",
            "Dark Stanley",
            "Sticky-Fingers Stella",
            "Unnamed Teacher",
            "Unnamed teacher with red glasses",
            "Zachary Vaughn"
          ],
          students: {
            secondGrade: [
              "\"Blow the Horn\" Kid",
              "Afro Girl",
              "Becky (Student)",
              "Beezee",
              "Chuck Berger",
              "Black Weasel",
              "Brittany Brockman",
              "Brown-haired boy",
              "Caitlin, Katelyn and Kate Lynn",
              "Report Card",
              "Coward",
              "Michael D'Amico",
              "E-mail",
              "Eliza",
              "Elizabeth Hoover's Students",
              "Freddy",
              "German Santa Girl",
              "Girl playing soccer",
              "Girl with necklace",
              "Gus Huebner",
              "Ham",
              "Hubert Wong",
              "Isabel Gutierrez",
              "Jake Boyman",
              "Jamie",
              "Lisa, Jr.",
              "Louie Junior",
              "Lucas Bortner",
              "My Ding-a-Ling Kid",
              "Janey Powell",
              "Ralph (Moaning Lisa)",
              "Ralph Wiggum",
              "Rex (I Love Lisa)",
              "Francine Rhenquist",
              "Sherri and Terri's sister",
              "Lisa Simpson",
              "Gold Star",
              "Summer Romance girl",
              "Cosine Tangent",
              "Tanya",
              "Allison Taylor",
              "Tumi",
              "Wanda",
              "White Kid",
              "White-Haired Girl",
              "Alex Whitney",
              "Yellow Weasel"
            ],
            thirdGrade: [
              "Ashley",
              "Ashley (3rd Grader)",
              "Audrey McConnell's Students",
              "Black Weasel",
              "Boy with glasses",
              "Brown-haired girl",
              "Dakota (Blond)",
              "Dakota (Orange)",
              "Girl with ponytail",
              "Kyle (3rd Grader)",
              "Kyle's Sister",
              "Melody Juniper",
              "Morgan (3rd Grader)",
              "Sara (Student)",
              "Little Moe Szyslak",
              "Neil Terwilliger",
              "Tyler (Female 3rd Grader)",
              "Tyler (Male 3rd Grader)",
              "Yellow Weasel"
            ],
            forthGrade: [
              "Amy",
              "Arthur",
              "Bart Simpson",
              "Adrian Belew",
              "Bashir bin Laden",
              "Bodhi",
              "Wendell Borton",
              "Boy with bangs",
              "Boy with freckles",
              "Boy with shades",
              "Kyle Broflovski",
              "Brown Long Haired Girl",
              "Buck-toothed boy",
              "Buck-toothed girl",
              "Eric Cartman",
              "Cool kid",
              "Cypress Creek Milhouse (A.K.A Milhouse look alike)",
              "Database",
              "Donny (The Debarted)",
              "Doo-De-Doo Kid",
              "Dr. Hibbert's Second Son",
              "Tobias Drundridge",
              "Edna Krabappel's Students",
              "Ezekiel",
              "Female Twin",
              "Rod Flanders",
              "Todd Flanders",
              "Girl with glasses",
              "Great Son",
              "Ishmael",
              "Jenda Simpson",
              "Kearney Zzyzwicz, Jr.",
              "Kenny McCormick",
              "Kevin (Stealing First Base)",
              "Lester",
              "Lewis Clark",
              "Lewis' lookalike",
              "Long-haired girl",
              "Jessica Lovejoy",
              "Sherri Mackleberry",
              "Terri Mackleberry",
              "Male Twin",
              "Stan Marsh",
              "Martin Prince",
              "Nikki McKenna",
              "Milhouse (Shelbyville)",
              "Nelson Muntz",
              "Nina Skalka",
              "Noah (Father Knows Worst)",
              "Photo Girl",
              "Rex (Bart of Darkness)",
              "Richard",
              "Sailor Kid",
              "Shelby",
              "Shelbyville boy",
              "Shelbyville lemonade boy's brother",
              "Shelbyville Martin",
              "Shelbyville Nelson",
              "Sherri and Terri",
              "Bart Simpson, Jr.",
              "Smug Girl",
              "Sophie Jensen",
              "Samantha Stankey",
              "Tommy",
              "Milhouse Van Houten",
              "Warren (Camper)",
              "Jaffee Ziswhisky",
              "Üter Zörker"
            ],
            fifthGrade: [
              "\"Where the Redfern Grows\" 5th grader",
              "5th grade girl",
              "Audrey McConnell's Student 4",
              "Danny",
              "Darryl",
              "Erik",
              "Jenny",
              "Kyle LaBianco",
              "Mike's Student 1",
              "Mike's Student 2",
              "Mike's Student 3",
              "Mr. Benzie's Students",
              "Ross",
              "Taffy",
              "Tyler (Moms I'd Like to Forget)",
              "Zack"
            ],
            sixthGrade: [
              "Rod Flanders",
              "Kearney Zzyzwicz"
            ]
            
          }
        },
        address: "742 Evergreen Terrace"
      },
      
    },
    category: {
      casinos: [
      "Caesar's Pow-Wow Casino",
      "Casino",
      "La Belle Frottage Casino",
      "Mr. Burns' Casino",
      "Nero's Palace",
      "Plato's Republic Casino",
      "Vic Tayback Hotel & Casino"
    ],
      hotels: [
        "Aphrodite Inn",
        "Bates Motel",
        "Bill & Edwina's Tour-Rest Cabins",
        "Boise Astoria",
        "Buckingham Pay-less Motel",
        "Capital City Plaza Hotel",
        "Dayton Arms Hotel",
        "Four Seasons",
        "Hotel",
        "Kozy Kabins",
        "Low Quality Inn",
        "Moeview Motel",
        "Motel",
        "Motel (Itchy & Scratchy)",
        "Palm Springfield Resort",
        "Peanut Street Hotel",
        "Pillowmint Hotel",
        "Rancho Relaxo",
        "Second-Best Western Hotel",
        "Sleep-Eazy Motel",
        "Smooches On The Beach",
        "Snuggler's Cove",
        "Springfield Four Seasons",
        "Springfield Inn",
        "Springfield Palace Hotel",
        "Starlight Motel",
        "Swell-Air Hotel",
        "The Benny Hilton",
        "The Happy Earwig Motel",
        "The Ritz-Carlton Hotel for Transients",
        "The Royal Fart Inn",
        "The Snowed Inn",
        "The Starlight Motel",
        "Vic Tayback Hotel & Casino",
        "Who's To Know Motel",
        "Woosterfield Hotel",
        "Ye Olde Off-Ramp Inn"
      ],
      bars: [
        "The Aristocrat",
        "Bar",
        "Comic Book Guy's Bar",
        "Crocodile Drunkee's",
        "Food Court",
        "Homer's Hunting Club",
        "Joe's Tavern",
        "Juggernauts",
        "Knockers",
        "Moab's",
        "Moe's Brewing Co.",
        "Moe's Express",
        "Moe's Tavern",
        "O'Flanagan's Pub",
        "P.F. Wangs",
        "Poppa Wheelie's",
        "She-She Lounge",
        "Shotkickers",
        "The Beer-N-Brawl",
        "The Bloated Liver",
        "The Dew Drop Bar",
        "The Gridiron",
        "The League of Extra Horny Gentleman",
        "The Little Black Box"
      ],
      resaurants: [
        "Arby's",
        "Asia de Cuba",
        "Bard Lad",
        "Berger's Burgers",
        "Big T Burgers & Fries",
        "Bloaters at the Squidport",
        "Burger King",
        "Burgers n' Fries",
        "Café Kafka",
        "Chez Paree",
        "Chili Blasters",
        "Chuck Dukewagon's All American Chow Lounge",
        "Cinnabun",
        "Clam-Elot Sea-Food",
        "Coffee & Tea",
        "Coffee Shop (Bowlarama)",
        "Coffee Shop (mall)",
        "Coffee Shop (Springfield Heights)",
        "Coffee Shop (Towne Centre)",
        "Cora's Diner",
        "Crouching Tiger Hidden Eggroll",
        "Dead Lobster",
        "Deluxe Sunday Brunch",
        "Dimwillie's",
        "Diner",
        "Dregs",
        "Drippin' Dots",
        "Drunken Donuts",
        "El Chemistri",
        "FaceStuffers",
        "Fish 'n' Chips",
        "Flickeys",
        "Food Court",
        "Forgotten Amos Cookies",
        "Fried Dough",
        "The Frying Dutchman",
        "Gas and Grub",
        "General Chang's Taco Italiano",
        "The Gilded Truffle",
        "Greaser's Cafe",
        "Greek Town",
        "Gulp 'n' Blow",
        "Haile Delicious Ethiopian Food",
        "Half-Man Half-Ape Burgers",
        "Hamburger Heaven",
        "The Happy Sumo",
        "Hot Dogs",
        "The Hungry Hun",
        "Ice Cream",
        "Ice Cream Parlor",
        "Inn",
        "Izzy's Deli",
        "Java the Hut",
        "Jazzy Goodtime's",
        "Jittery Joe's Coffee Shop",
        "Joe's Diner",
        "Johnny Fiestas",
        "Kentucky Fried Chicken",
        "Kentucky Fried Panda",
        "Kooky Cat's Deli-cat-essen",
        "Krusty Burger",
        "Krusty Burger Oil Rig",
        "Krusty Fried Chicken",
        "Lard Lad Donuts",
        "Le Krusty Burger",
        "Le Petite Appétit",
        "Leaning Tower of Pizza",
        "Luigi's",
        "Madame Chao's",
        "Magic Palace",
        "Malaria Zone",
        "Medieval Times",
        "Mickey Mao's",
        "Moe's Tavern",
        "Mother Hubbard's Sandwich Cupboard",
        "Much Ado About Muffins!",
        "Municipal House of Pancakes",
        "Nighthawk Diner",
        "O'Flanagan's Pub",
        "Odd Ones",
        "Odyssey Diner",
        "Overpass Diner",
        "P. Piggly Hogswine's Super-Smorg",
        "The Penny Loafer",
        "Phineas Q. Butterfat's 5600 Flavors Ice Cream Parlor",
        "The Pimento Grove",
        "Pinkbeardy Yogurt",
        "Pizzeria Cheapo",
        "Planet Hype",
        "Planet Springfield",
        "Pretzel Wagon",
        "Professor V.J. Cornucopia's Fantastic Foodmagorium and Great American Steakery",
        "Pudding on the Ritz",
        "R. Crumb's Keep on Muffin'",
        "The Rusty Barnacle",
        "S.N.P.P. Cafeteria",
        "Sha-Boom Ka-Boom! Cafe",
        "Shorty's",
        "The Singing Sirloin",
        "Sir Duncan's Doughed Naughts",
        "Sit-N-Rotate",
        "Skip's Diner",
        "Skobo's",
        "Skybucks",
        "The Slaughterhouse",
        "Snack Shack",
        "The Spaghetti Laboratory",
        "Splitsville Icecream Sundaes",
        "Springfield Dinner Theater",
        "Sprubway",
        "Spruce Caboose",
        "Stuckey's",
        "Swanky Fish",
        "Taj Mah-All-You-Can-Eat",
        "Tavern on the Scream",
        "Tern For The Wurst Delicatessen",
        "The Buzzing Sign Diner",
        "The Cloth Napkin",
        "The Enchanted Snail",
        "The Fifth Helping",
        "The Java Server",
        "The Kabuli Palow",
        "The Loin King",
        "The Picky Vegan",
        "The Seething Sisters",
        "Tsarbucks",
        "Two Guys From Kabul",
        "Ugli",
        "Uncle Moe's Family Feedbag",
        "Up, Up and Buffet!",
        "Vesuvius Pizza",
        "Wall E. Weasel's",
        "We Have Restrooms!",
        "You Thai Now",
        "Yumí Ristorante",
        "Zesty's",
        "Zip Zap and 'Za Pizza Arcade"
      ],
      education: [
        "Adult Education Annex",
        "Asteroid Elementary",
        "Ayn Rand School for Tots",
        "Burns University",
        "Chazz Busby Ballet Academy",
        "Cloisters Academy",
        "Cypress Creek Elementary School",
        "Day-Care Center",
        "Enriched Learning Center for Gifted Children",
        "Hellroads",
        "Hollywood Upstairs Medical College",
        "Karate",
        "Krusty's Clown College",
        "Krusty's Kids Daykare",
        "Leavelle's Bodyguard Academy",
        "Li'l Ludwig's Music School",
        "List of Springfield Elementary Faculty Members",
        "Mensa International",
        "MIT",
        "Montessori School",
        "Mrs. Wickerbottom's Pre-Nursery School",
        "Onward Christian Schoolboys Academy",
        "Oral Roberts University",
        "Pitiless Pup Attack Dog School",
        "Preschool",
        "Rommelwood Military School",
        "Saint Sebastian's School for Wicked Girls",
        "Santa School",
        "Shelbyville Elementary School",
        "Springfield A&M",
        "Springfield Arts Center",
        "Springfield Barber College",
        "Springfield Christian School",
        "Springfield Community College",
        "Springfield Creative Arts Academy",
        "Springfield Elementary School",
        "Springfield Elementary School and Prison",
        "Springfield Extension School",
        "Springfield Heights Institute of Technology",
        "Springfield High School",
        "Springfield Magnet School",
        "Springfield Police Academy",
        "Springfield Preparatory School",
        "Springfield School for the Deaf",
        "Springfield University",
        "Springwarts School of Magicry",
        "St. Jerome's Catholic School",
        "Stonecutter's Daycare Center",
        "Swigmore University",
        "Teacher Holding Facility",
        "Tuition Academy",
        "University of Michigan",
        "Waverly Hills Elementary School",
        "West Springfield Elementary School",
        "Yale University"
      ],
      themeParks: [
        "Blockoland",
        "Chlorine Dreams Indoor Water Park",
        "Cretaceous Park",
        "Discount Lion Safari",
        "Diz-Nee Land",
        "Duff Gardens",
        "EFCOT Center",
        "Euro-Itchy & Scratchy Land",
        "Family Fun Center",
        "Itchy & Scratchy Land (Theme Park)",
        "Krustyland",
        "LEGOLAND",
        "Lisa Land",
        "Mt. Splashmore",
        "Plaster Mountain Theme Park",
        "Praiseland",
        "Santa's Village",
        "Sir Putt-A-Lot's Merrie Olde Fun Centre",
        "Six Flags Over Krusty",
        "Springfield Cabbage Festival",
        "Storytown Village",
        "Universal Studios",
        "Wet 'N' Wacky World"
      ]
    }
  }
}

module.exports = simpsons;